sudo: false
language: python
python:
  - '3.6'
# command to install dependencies
install:
  - pip install --upgrade --pre tox
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://open.stridespace.com
  
# # command to run tests
env:
  matrix:
    # coveralls is not listed in tox's envlist, but should run in travis
    - TOXENV=coveralls
    # note: please use "tox --listenvs" to populate the build matrix below
    - TOXENV=linting
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py36
    - TOXENV=py27-pexpect
    - TOXENV=py27-xdist
    - TOXENV=py27-trial
    - TOXENV=py27-numpy
    - TOXENV=py36-pexpect
    - TOXENV=py36-xdist
    - TOXENV=py36-trial
    - TOXENV=py36-numpy
    - TOXENV=py27-nobyte
    - TOXENV=doctesting
    - TOXENV=docs

matrix:
  include:
    - env: TOXENV=py26
      python: '2.6'
    - env: TOXENV=py33
      python: '3.3'
    - env: TOXENV=pypy
      python: 'pypy-5.4'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py35-freeze
      python: '3.5'
    - env: TOXENV=py37
      python: 'nightly'
  allow_failures:
    - env: TOXENV=py37
      python: 'nightly'

script: tox --recreate

after_script:
  - |
    if [[ $TOXENV == "py"* || $TOXENV = "coveralls" ]]; then
      testspace [$TOXENV]testing/results.xml{testing}
    fi
    
notifications:
  email: false
  irc: false
